# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7e85d16b573111f54d992d9b7ef40ae607b83679cd9c0f24c5cf4d4f3848569b94fd1ca856f25a2c00f96da364a639860e476920302ea02f8b2f5dab4d2dabcd

test:
  secret_key_base: 520e293753f7d10d841c191049c60f0d59c0014c090c89c0635f154e21e88ddf7d90753d7ab9366815090dd16c100bd0f6dbb1c6e38df7844f799f6561b0abe3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
